create database hicouncelor;
use hicouncelor;

CREATE TABLE apps_data (
	App VARCHAR(200) NOT NULL, 
	Category VARCHAR(25) NOT NULL, 
	Rating DECIMAL(38, 1) NOT NULL, 
	Reviews DECIMAL(38, 0) NOT NULL, 
	Size VARCHAR(20) NOT NULL, 
	Installs DECIMAL(38, 0) NOT NULL, 
	`Type` VARCHAR(5) NOT NULL, 
	Price DECIMAL(38, 2) NOT NULL, 
	Content_Rating VARCHAR(20) NOT NULL, 
	Genres VARCHAR(40) NOT NULL, 
	Last_Updated VARCHAR(10) NOT NULL, 
	Current_Ver VARCHAR(50) NOT NULL, 
	Android_Ver VARCHAR(20) NOT NULL
);

CREATE TABLE reviews_data (
	App VARCHAR(150) NOT NULL, 
	Translated_Review VARCHAR(2686) NOT NULL, 
	Sentiment VARCHAR(10) NOT NULL, 
	Sentiment_Polarity DECIMAL(38, 3) NOT NULL, 
	Sentiment_Subjectivity DECIMAL(38, 3) NOT NULL
);


SET SESSION sql_mode = '';    
SET SQL_SAFE_UPDATES = 0;

-- Inserting Data into file
LOAD DATA INFILE 'D:/preprocessed_apps_data.csv'
into table apps_data
FIELDS TERMINATED by ','
ENCLOSED by '"'
lines terminated by '\n'
IGNORE 1 ROWS;

LOAD DATA INFILE 'D:/preprocessed_reviews_data.csv'
into table reviews_data
FIELDS TERMINATED by ','
ENCLOSED by '"'
lines terminated by '\n'
IGNORE 1 ROWS;

-- Logic for changing datatype of Last_Update column
 alter table apps_data
 add column Last_Updated2 date after Last_Updated;
 
 update apps_data
 set Last_Updated2 = str_to_date(Last_Updated, "%d-%m-%Y");
 
 alter table apps_data
 drop Last_Updated;

select * from apps_data ;

select* from reviews_data;


-- Also i have noticed that apps_data table has redundent data so creating a view with logic to remove redundent values 
-- and will be using it for analysis

create or replace view apps_data_view as(
select *
from(
	select *,
	row_number() over(partition by App order by Reviews desc) as rn
	from apps_data) x
where rn = 1);


select count(*) from apps_data;
select count(*) from apps_data_view;


-- 1) Which apps have the highest rating in the given available dataset?

select distinct App
from apps_data_view
where Rating = (select max(Rating) from apps_data_view);

-- 2) What are the number of installs and reviews for the above apps? Return the apps with the highest reviews to the top

select App, max(Installs), max(Reviews)
from apps_data_view
group by App
order by Reviews desc;

-- 3) Which app has the highest number of reviews? Also, mention the number of reviews and category of the app

select App , Category, sum(Reviews)
from apps_data_view
group by 1,2
order by 3 desc
limit 1;

-- 4) What is the total amount of revenue generated by the google play store by hosting apps? 
--    (Whenever a user buys apps  from the google play store, the amount is considered in the revenue)

select sum(Price*Installs) as Revenue
from apps_data_view
where Type = 'Paid';

-- 5) Which Category of google play store apps has the highest number of installs? 
--    also, find out the total number of installs for that particular category.

select Category, sum(Installs)
from apps_data_view
group by 1
order by 2 desc
limit 1;

-- 6) Which Genre has the most number of published apps?

select Category, count(distinct App)
from apps_data_view
group by 1
order by 2 desc
limit 1;

-- 7) Provide the list of all games ordered in such a way that the game that has the highest number of installs is displayed on the top
--    (to avoid duplicate results use distinct)

select  distinct App, sum(Installs)
from apps_data_view
where Category = 'GAME'
group by 1
order by 2 desc;

-- 8) Provide the list of apps that can work on android version 4.0.3 and UP.

select distinct App
from apps_data_view
where Android_Ver like '%4.0.3 and up%';

-- 9) How many apps from the given data set are free? Also, provide the number of paid apps.

select Type, count( distinct App)
from apps_data_view
group by 1;

-- 9) Which is the best dating app? (Best dating app is the one having the highest number of Reviews)

select App, Category, max(Reviews) as Tot_Reviews
from apps_data_view
where Category = 'DATING'
group by App
order by Reviews desc
limit 1;

-- 10) Get the number of reviews having positive sentiment and number of reviews having negative sentiment for 
--     the app 10 best foods for you and compare them.

select App, 
		sum(case when Sentiment = 'Positive' then 1 else 0 end) as Positive_Sentiment,
        sum(case when Sentiment = 'Negative' then 1 else 0 end) as Negative_Sentiment
from reviews_data
where App ='10 Best Foods for You'
group by App;

-- 12) Which comments of ASUS SuperNote have sentiment polarity and sentiment subjectivity both as 1?

select App, Translated_Review as Comments
from reviews_data
where App like '%ASUS SuperNote%' and Sentiment_Polarity = '1' and Sentiment_Subjectivity = '1';

-- 13) Get all the neutral sentiment reviews for the app Abs Training-Burn belly fat 

select App, Translated_Review as Review
from reviews_data
where App like 'Abs Training-Burn belly fat%' and Sentiment = 'Neutral';

-- 14) Extract all negative sentiment reviews for Adobe Acrobat Reader with their sentiment polarity and sentiment subjectivity

select App, Translated_Review as Review, Sentiment_Polarity, Sentiment_Subjectivity
from reviews_data
where App like '%Adobe Acrobat Reader%' and Sentiment = 'Negative';





